FROM sbtscala/scala-sbt:graalvm-ce-22.3.3-b1-java17_1.12.0_3.7.4 AS build

WORKDIR /chess
COPY . /chess

RUN sbt -batch update

RUN sbt -batch assembly

FROM eclipse-temurin:21-jre-jammy

RUN apt-get update && apt-get install -y --no-install-recommends \
    xvfb fluxbox x11vnc novnc websockify \
    libgtk-3-0 libxrender1 libxtst6 libxi6 libxrandr2 libasound2 \
    libgl1 libgl1-mesa-dri \
    fonts-dejavu \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /chess/target/scala-*/chess-assembly-*.jar /app/app.jar

COPY docker/start.sh /app/start.sh
RUN chmod +x /app/start.sh
RUN chmod +x /app/start.sh

EXPOSE 5900 6080

ENV DISPLAY=:0
CMD ["/app/start.sh"]